<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>primetime43_Ratchet_Clank_Save_Editor</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationIcon>Ratchet.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="../docs/maps/ToolsOfDestruction.BCUS98127.v02.00.json" LogicalName="Research.Tod.Map.json" />
    <EmbeddedResource Include="../docs/maps/ToolsOfDestruction.BCUS98127.v02.00.WeaponConfigs.json" LogicalName="Research.Tod.Configs.json" />
    <EmbeddedResource Include="../docs/ToolsOfDestructionElfMap.md" LogicalName="Research.Tod.ElfNotes.md" />
    <EmbeddedResource Include="../docs/ToolsOfDestructionSaveFormat.md" LogicalName="Research.Tod.SaveNotes.md" />
  </ItemGroup>
</Project>
