<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>primetime43_Ratchet_Clank_Save_Editor</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationIcon>Ratchet.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="../docs/PS3/ToolsOfDestruction/BCUS98127/v02.00/maps/NativeMap.json" LogicalName="Research.Tod.Map.json" />
    <EmbeddedResource Include="../docs/PS3/ToolsOfDestruction/BCUS98127/v02.00/maps/WeaponConfigs.json" LogicalName="Research.Tod.Configs.json" />
    <EmbeddedResource Include="../docs/PS3/ToolsOfDestruction/BCUS98127/v02.00/ElfMap.md" LogicalName="Research.Tod.ElfNotes.md" />
    <EmbeddedResource Include="../docs/PS3/ToolsOfDestruction/SaveFormat.md" LogicalName="Research.Tod.SaveNotes.md" />
  </ItemGroup>
</Project>
